version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: user
       MYSQL_DATABASE: ratadb
       MYSQL_USER: user
       MYSQL_PASSWORD: user

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes: 
      - ./wordpress:/var/www/html
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: user
       WORDPRESS_DB_PASSWORD: user
       WORDPRESS_DB_NAME: ratadb
volumes:
    db_data: {}
